from enum import Enum


class ResponseType(Enum):
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS"
    RESOURCE_CREATED = "RESOURCE_CREATED"
    RESOURCE_FOUND = "RESOURCE_FOUND"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    WRONG_PAYLOAD = "WRONG_PAYLOAD"
    SUCCESS = "SUCCESS"
    UNAUTHORIZED = "UNAUTHORIZED"
